# Generated by Django 4.2.11 on 2024-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_name_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth0_user_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
